apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: auth
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi